[package]
name = "vegravis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.22.0", default-features = false, features = [
    "__screenshot",
    "default_fonts",
    "wgpu",
] }
egui_extras = "0.22.0"
egui_code_editor = "0.1.2"

env_logger = "0.10.0"

